#
# Copyright (C) 2019-2020 Woods Hole Oceanographic Institution
#
# This file is part of the Roundabout Database project ("RDB" or
# "ooicgsn-roundabout").
#
# ooicgsn-roundabout is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ooicgsn-roundabout is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ooicgsn-roundabout in the COPYING.md file at the project root.
# If not, see <http://www.gnu.org/licenses/>.
#

version: '3.7'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}
  static_volume: {}
  media_volume: {}

services:
  django: &django
    image: ghcr.io/whoigit/ooicgsn-roundabout:stable
    #container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume:/app/staticfiles  # <-- bind the static files
      - media_volume:/app/media  # <-- bind the media files
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    restart: unless-stopped
    command: /start
    networks:
      - roundabout-network

  postgres:
    image: ghcr.io/whoigit/postgres-docker-scripts:10.5
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped
    networks:
      - roundabout-network

  redis:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - roundabout-network

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    command: /start-flower

  nginx:
    image: nginx:1.15
    container_name: nginx
    depends_on:
      - django
    volumes:
      - production_nginx:/var/log/nginx # logs
      - ./nginx:/etc/nginx/conf.d:ro
      - ./.ssl/certs:/etc/ssl/certs:ro # bind a local directory with the WHOI SSL certs
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    restart: unless-stopped
    networks:
      - roundabout-network

networks:
  roundabout-network:
    name: roundabout-network
    driver: bridge
