#
# Copyright (C) 2019-2020 Woods Hole Oceanographic Institution
#
# This file is part of the Roundabout Database project ("RDB" or
# "ooicgsn-roundabout").
#
# ooicgsn-roundabout is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ooicgsn-roundabout is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ooicgsn-roundabout in the COPYING.md file at the project root.
# If not, see <http://www.gnu.org/licenses/>.
#

# rdb-demo.whoi.edu containers
# requires the main roundabout-network to be running
version: '3.5'

volumes:
  production_postgres_data_demo: {}
  production_postgres_data_backups_demo: {}
  static_volume_demo: {}
  media_volume_demo: {}

services:
  django_demo:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: roundabout_demo_django
    container_name: django_demo
    depends_on:
      - postgres_demo
    volumes:
      - static_volume_demo:/app/staticfiles  # <-- bind the static files
      - media_volume_demo:/app/media  # <-- bind the media files
    env_file:
      - ./.envs/.production/.django_demo
      - ./.envs/.production/.postgres_demo
    restart: unless-stopped
    command: /start

  postgres_demo:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: roundabout_demo_postgres
    container_name: postgres_demo
    volumes:
      - production_postgres_data_demo:/var/lib/postgresql/data
      - production_postgres_data_backups_demo:/backups
    env_file:
      - ./.envs/.production/.postgres_demo
    restart: unless-stopped

networks:
  default:
    external:
      name: roundabout-network
