version: 2

workflows:
  version: 2
  test:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          # From https://circleci.com/docs/2.0/docker-compose/
          name: Installing Docker Compose
          command: >-
            DC_VERSION=1.19.0 &&
            DC_DOWNLOAD=docker-compose-`uname -s`-`uname -m` &&
            curl -Lo ~/docker-compose \
              https://github.com/docker/compose/releases/download/$DC_VERSION/$DC_DOWNLOAD &&
            chmod +x ~/docker-compose &&
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Building Docker application
          command: >-
            mv .envs.example .envs &&
            docker-compose --file local.yml build
      - run:
          # The Django start script will run migrations for us
          name: Starting Docker application
          command: >-
            docker-compose --file local.yml up
      - run:
          name: Checking for missing migrations
          command: >-
            docker-compose --file local.yml run --rm django \
              python manage.py makemigrations --check
      - run:
          name: Running Django system checks
          command: >-
            docker-compose --file local.yml run --rm django \
              python manage.py check
      - run:
          name: Running Django tests
          command: >-
            docker-compose --file local.yml run --rm django \
              python manage.py test
      - run:
          name: Stopping Docker application
          command: >-
            docker-compose --file local.yml down
