# Generated by Django 4.2.13 on 2024-07-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0023_auto_20220302_1812'),
        ('inventory', '0081_auto_20221121_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='cruise_deployed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='cruises.cruise'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='cruise_recovered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_%(class)ss', to='cruises.cruise'),
        ),
        migrations.AlterField(
            model_name='inventorydeployment',
            name='cruise_deployed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='cruises.cruise'),
        ),
        migrations.AlterField(
            model_name='inventorydeployment',
            name='cruise_recovered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_%(class)ss', to='cruises.cruise'),
        ),
    ]
