# Generated by Django 3.1.3 on 2023-12-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_auto_20231212_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='surveyed_ldepth',
            new_name='surveyed_depth',
        ),
    ]
