# Generated by Django 4.2.13 on 2025-10-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_alter_deployment_cruise_deployed_and_more'),
        ('inventory', '0083_auto_20231212_1941'),
    ]

    operations = [
    ]
