# Generated by Django 4.2.13 on 2024-07-15 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_auto_20221121_2151'),
        ('parts', '0020_part_bulk_upload_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemblies', '0016_auto_20221121_2151'),
        ('configs_constants', '0028_merge_20210610_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdefaultevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_%(class)ss', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_%(class)ss', to='inventory.deployment'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_%(class)ss', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_%(class)ss', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configdefaultevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_%(class)ss', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_%(class)ss', to='inventory.deployment'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_%(class)ss', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_%(class)ss', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_%(class)ss', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_%(class)ss', to='inventory.deployment'),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_%(class)ss', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_%(class)ss', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confignameevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_%(class)ss', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_%(class)ss', to='inventory.deployment'),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_%(class)ss', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_%(class)ss', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constdefaultevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
