# Generated by Django 4.2.13 on 2024-07-15 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assemblies', '0016_auto_20221121_2151'),
        ('ooi_ci_tools', '0027_auto_20220307_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkuploadevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruiseevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cruiseevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencedesignatorevent',
            name='assembly_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblypart_%(class)ss', to='assemblies.assemblypart'),
        ),
        migrations.AlterField(
            model_name='referencedesignatorevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referencedesignatorevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='user_approver',
            field=models.ManyToManyField(related_name='approver_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='user_draft',
            field=models.ManyToManyField(blank=True, related_name='reviewer_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
