name: Create and publish a package
on:
  push:
    branches: 
      - 'release-**'
      - 'automated_tests'

env:
  IMAGE_NAME: ooicgsn-roundabout

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Running Automated tests
        run:  |
          google-chrome --version
          chromedriver --version
          echo node.exe version
          node -v
          echo

          # Build and run development version of Django
          mv .envs.example .envs
          docker-compose -f docker-compose-testing.yml build
          docker-compose -f docker-compose-testing.yml up --detach
          sleep 60

          # Run automated tests
          docker-compose -f docker-compose-testing.yml run tests ./RunAllTests-Chrome-Linux.bat

      - name: Build, Tag & Push Production Image
        if: contains(github.ref, 'release')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}
        
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from branch
          BRANCH=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "release-" prefix from version
          VERSION=$(echo $BRANCH | sed -e 's/.*-//')

          echo "IMAGE_ID:"
          echo $IMAGE_ID
          echo "VERSION:"
          echo $VERSION

          # Build Production Django Container
          docker build -f compose/production/django/Dockerfile -t $IMAGE_ID .

          docker image ls
                        
          docker tag $IMAGE_ID $IMAGE_ID:$VERSION

          docker push $IMAGE_ID:$VERSION

      - name: Stopping Docker application
        run:  docker-compose --file docker-compose-testing.yml down

