name: Create and publish a package
on:
  push:
#    branches: ['release']
    branches: ['automated_tests']

# Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: ooicgsn-roundabout

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building Docker application
        run: |
            mv .envs.example .envs
            docker-compose --file local.yml build

      - name: Starting Docker application
        # The Django start script will run migrations for us
        run: docker-compose --file local.yml up --detach

      - name: Check for missing migrations
        run: |
          docker-compose --file local.yml run --rm django python manage.py makemigrations --check

      - name: Running Django system checks
        run: |
          docker-compose --file local.yml run --rm django python manage.py check

      - name: Running Django tests
        run: |
          docker-compose --file local.yml run --rm django python manage.py test

      - name: Running Automated tests
        run:  |
          google-chrome --version
          chromedriver --version
          echo node.exe version
          node -v
          echo
          docker-compose -f docker-compose-testing.yml build tests
#          docker-compose -f docker-compose-testing.yml run --rm tests ./RunAllTests-Chrome-Linux.bat

      - name: Push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}
        
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo $github.ref

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo $IMAGE_ID
          echo $VERSION
            
          docker tag $IMAGE_ID $IMAGE_ID:$VERSION
          docker image ls
          # Push release branches only
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && docker push $IMAGE_ID:$VERSION

#          docker push $IMAGE_ID:$VERSION

          # Push release branches only
#          [ startsWith( "$VERSION", "release" ) ] && docker push $IMAGE_ID:$VERSION

      - name: Stopping Docker application
        run:  docker-compose --file local.yml down

